project:
  type: website
  output-dir: docs

website:
  title: "Namaah's website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: Resume
      - href: projects.qmd
        text: My Projects

    
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




